--- 
extensions: 
- extension-name-here
- second-extension-name
name: Rutanet
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.0.0.beta11
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.0.0
iphone: 
  provisionprofile: BAB777EC-1213-4FF1-AC2B-0DDF4027A709
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: "iPhone Developer: Federico Gonzalez (TFGDBWF93W)"
  configuration: Debug
