sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-2.0.0.beta7"
sdkversion: 2.0.0
name: Rutanet
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  provisionprofile: BAB777EC-1213-4FF1-AC2B-0DDF4027A709
  codesignidentity: "iPhone Developer: Federico Gonzalez (TFGDBWF93W)"
  entitlements:
extensions: ["extension-name-here", "second-extension-name"]
