--- 
name: Rutanet
extensions: 
- extension-name-here
- second-extension-name
bbver: 4.6
sdk: /Users/Adrian/.rvm/gems/ruby-1.8.7-p174/gems/rhodes-2.0.0
build: debug
applog: rholog.txt
version: 1.1
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.0.0
vendor: rhomobile
iphone: 
  provisionprofile: xxx
  sdk: iphonesimulator3.0
  codesignidentity: "xxx"
  entitlements: 
  configuration: Debug
